### ISSUE TITLE
Linking not completing

### ISSUE THREAD

**Issue by IGx89** [sogaani/mozassist#4]
I successfully went through the whole linking process, including the Authorization prompt screen on my gateway, but when it redirected back to the Google Home app it said "Something went wrong. Please try again". I've tried it multiple times to no avail. Do you have logs that show anything amiss?

Thanks!

**Comment by sogaani** [comment]
@IGx89 
Thank you for notifying this issue.
Mozassist didn't keep up with [Web Thing API](https://iot.mozilla.org/wot/) and failed to communicate with Gateway.
I supported the latest Web Thing API. It seems to work fine. Hopefully also fine with you.

Thanks!

**Comment by IGx89** [comment]
Totally understand that, a lot can change in a year! Thanks for updating it -- I'll test it out again tonight and let you know how it goes.

**Comment by IGx89** [comment]
That did the trick, thanks a lot! And thanks a lot for making this Smart Home action, really cool what you were able to do :)
